const MA_DB="ma11files",MA_KEY="ma11";
const M=$=>document.getElementById($);
const maOpen=async()=>new Promise((res,rej)=>{const r=indexedDB.open(MA_DB,1);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});
const maPut=async(id,file)=>{const db=await maOpen();return new Promise((res,rej)=>{const tx=db.transaction("f","readwrite");tx.objectStore("f").put(file,id);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})};
const maMoney=n=>new Intl.NumberFormat("de-CH",{style:"currency",currency:"CHF",minimumFractionDigits:2}).format(Number(n)||0);
const maEsc=s=>String(s??"").replace(/[&<>\"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;","'":"&#39;"}[m]));
function maType(t){const x=t.toLowerCase();if(/mahnung|zahlungserinnerung|letzte zahlungserinnerung/.test(x))return"Mahnung";if(/kreditkarte|credit card|kartenabrechnung|card statement|visa|mastercard|cembra/.test(x))return"Kreditkartenabrechnung";if(/arbeitsvertrag|mietvertrag|kaufvertrag|vertrag|vereinbarung/.test(x))return"Vertrag";if(/versicherung|police|policenummer|police\s*nr|versicherungsnummer|prämienrechnung/.test(x))return"Versicherung";if(/lohnabrechnung|gehaltsabrechnung|lohnausweis|salary statement/.test(x))return"Lohnabrechnung";if(/garantie|garantieschein|kaufbeleg|kassenbon|quittung/.test(x))return"Kaufbeleg / Garantie";if(/kontoauszug|bankauszug|zinsabrechnung/.test(x))return"Bankdokument";if(/steuer|steueramt|veranlagung|behörde|gemeinde|kanton|bundesamt/.test(x))return"Behörde / Steuer";if(/rechnung|rechnungsbetrag|zahlbar bis|zahlungsziel|zu bezahlen/.test(x))return"Rechnung";return"Dokument"}
function maCat(type){return ({"Rechnung":"Rechnungen","Kreditkartenabrechnung":"Finanzen","Mahnung":"Mahnungen","Vertrag":"Verträge","Versicherung":"Versicherungen","Lohnabrechnung":"Finanzen","Kaufbeleg / Garantie":"Käufe & Garantien","Bankdokument":"Finanzen","Behörde / Steuer":"Behörden"}[type]||"Sonstiges")}
function maExtractType(text){const type=maType(text),x=text.toLowerCase();let status="Archiviert";if(type==="Mahnung")status=/letzte\s+mahnung|letzte\s+zahlungserinnerung/.test(x)?"Letzte Mahnung":/2\.\s*mahnung|zweite\s+mahnung|mahnsufe\s*2/.test(x)?"Mahnstufe 2":"Mahnstufe 1";return{type,cat:maCat(type),status}}
function maRender(){const data=JSON.parse(localStorage.getItem(MA_KEY)||"[]"),q=(M("search")?.value||"").toLowerCase(),list=M("list");if(!list)return;const items=data.filter(x=>!q||(x.name+" "+x.no+" "+x.cat+" "+x.type+" "+x.status).toLowerCase().includes(q));list.innerHTML=items.length?items.map(x=>{const d=x.paid?"paid":x.type==="Mahnung"?"danger":"future";const details=[x.amount?maMoney(x.amount):"",x.due?new Date(x.due+"T00:00:00").toLocaleDateString("de-CH"):"",x.no?"Nr. "+maEsc(x.no):""].filter(Boolean).join(" · ");return `<article class="doc"><b>${maEsc(x.name||x.file)}</b><div class="amount">${x.amount?maMoney(x.amount):"📄 Dokument"}</div><div class="muted">${maEsc(x.type||"Dokument")} · ${maEsc(x.cat||"Sonstiges")}${details?"<br>"+details:""}</div><span class="badge ${d}">${x.status||"Archiviert"}</span><div class="actions"><button class="btn outline" onclick="openPDF('${x.id}')">📄 Öffnen</button><button class="btn ${x.paid?'gray':'green'}" onclick="maToggle('${x.id}')">${x.paid?"↩ Wieder öffnen":"✓ Als erledigt markieren"}</button></div></article>`}).join(""):"<div class='empty'>Keine Dokumente.</div>";const open=data.filter(x=>!x.paid&&x.type!=="Dokument"),sum=open.reduce((a,x)=>a+(+x.amount||0),0);M("openCount").textContent=open.length;M("openAmount").textContent=maMoney(sum);M("soonCount").textContent=data.filter(x=>!x.paid&&x.due).length}
window.maToggle=id=>{const data=JSON.parse(localStorage.getItem(MA_KEY)||"[]"),x=data.find(a=>a.id===id);if(x){x.paid=!x.paid;x.paidDate=x.paid?new Date().toISOString().slice(0,10):"";localStorage.setItem(MA_KEY,JSON.stringify(data));maRender()}};
function maFindDocNumber(t,type){const patterns=type==="Versicherung"?[
  /(?:Policenummer|Police\s*(?:Nr\.?|Nummer)|Policen\s*(?:Nr\.?|Nummer)|Versicherungsnummer|Versicherung\s*(?:Nr\.?|Nummer)|Vertragsnummer|Vertrag\s*(?:Nr\.?|Nummer))\s*[:#-]?\s*([A-Z0-9][A-Z0-9\-\/ .]{3,35})/i,
  /(?:Police|Police-Nr\.?|Police\s*Nr\.?)\s*[:#-]?\s*([A-Z0-9][A-Z0-9\-\/]{3,35})/i
]:[/\b(?:Rechnungsnummer|Rechnung\s*(?:Nr\.?|Nummer)|Abrechnungsnummer|Abrechnung\s*(?:Nr\.?|Nummer))\s*[:#-]?\s*([A-Z0-9][A-Z0-9\-\/ ]{5,30})/i];for(const p of patterns){const m=t.match(p);if(m)return m[1].replace(/\s+/g," ").trim()}return""}
function maAddPreview(file){let a=M("filePreview");if(!a){a=document.createElement("a");a.id="filePreview";a.className="btn outline wide";a.target="_blank";a.rel="noopener";a.style.display="block";a.style.textAlign="center";a.style.textDecoration="none";a.style.marginTop="10px";file.parentNode.insertBefore(a,file.nextSibling)}a.href=URL.createObjectURL(file);a.textContent="👁️ Dokumentvorschau öffnen";a.hidden=false}
(async()=>{await new Promise(r=>setTimeout(r,50));const file=M("file"),oldChange=file?.onchange,oldSave=M("save")?.onclick;if(!file)return;const header=document.querySelector("header p");if(header)header.textContent="Dein persönliches Dokumenten- & Rechnungsarchiv · v17";document.title="MeinArchiv v17";
const typeWrap=document.createElement("div");typeWrap.innerHTML='<label>Dokumenttyp</label><select id="docType"><option>Automatisch erkennen</option><option>Rechnung</option><option>Kreditkartenabrechnung</option><option>Mahnung</option><option>Vertrag</option><option>Versicherung</option><option>Lohnabrechnung</option><option>Kaufbeleg / Garantie</option><option>Bankdokument</option><option>Behörde / Steuer</option><option>Dokument</option></select>';const cat=M("cat");cat?.parentNode?.insertBefore(typeWrap,cat);const type=M("docType");
file.onchange=async e=>{await oldChange?.(e);const f=file.files[0];if(!f)return;maAddPreview(f);let text="";try{if(f.type==="application/pdf"){const p=await import("https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.min.mjs");p.GlobalWorkerOptions.workerSrc="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.worker.min.mjs";const pdf=await p.getDocument({data:await f.arrayBuffer()}).promise;for(let i=1;i<=pdf.numPages;i++){const c=await(await pdf.getPage(i)).getTextContent();text+=c.items.map(a=>a.str).join(" ")+"\n"}}else{const{createWorker}=await import("https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.esm.min.js");const w=await createWorker("deu+eng+fra"),r=await w.recognize(await f.arrayBuffer());text=r.data.text||"";await w.terminate()}}catch{}const d=maExtractType(text+" "+f.name);type.value=d.type;if(type.value!==d.type)type.value="Dokument";
if(d.type==="Versicherung"){M("amount").value="";M("due").value="";const n=maFindDocNumber(text,d.type);if(n)M("no").value=n;const lab=[...document.querySelectorAll("label")].find(x=>x.textContent.trim()==="Rechnungsnummer");if(lab)lab.textContent="Policen-/Vertragsnummer";if(M("preview"))M("preview").innerHTML=`<hr><b>🧠 Dokumenttyp:</b> Versicherung · <b>Kategorie:</b> Versicherungen<br>🛡️ Policen-/Vertragsnummer: ${maEsc(M("no").value||"nicht erkannt")}<br>💰 Kein Rechnungsbetrag aus der Police übernommen.<br><span class="muted">👁️ Vorschau kann oben direkt geöffnet werden.</span>`;
}else{const lab=[...document.querySelectorAll("label")].find(x=>/Policen-\/Vertragsnummer|Dokumentnummer/.test(x.textContent));if(lab)lab.textContent="Rechnungsnummer";if(M("preview")){const old=M("preview").innerHTML;M("preview").innerHTML=old+`<hr><b>🧠 Dokumenttyp:</b> ${maEsc(d.type)} · <b>Kategorie:</b> ${maEsc(d.cat)} · <b>Status:</b> ${maEsc(d.status)}<br><span class="muted">👁️ Vorschau kann oben direkt geöffnet werden.</span>`}}
};
if(type)type.onchange=()=>{if(type.value!=="Automatisch erkennen"&&M("cat"))M("cat").value=maCat(type.value);if(type.value==="Versicherung"){M("amount").value="";M("due").value="";const lab=[...document.querySelectorAll("label")].find(x=>x.textContent.trim()==="Rechnungsnummer");if(lab)lab.textContent="Policen-/Vertragsnummer"}};
M("save").onclick=async()=>{const chosen=type.value==="Automatisch erkennen"?"Dokument":type.value;if(["Rechnung","Kreditkartenabrechnung"].includes(chosen)){await oldSave?.();const data=JSON.parse(localStorage.getItem(MA_KEY)||"[]");if(data[0]){data[0].type=chosen;data[0].status="Offen";data[0].cat=maCat(chosen)}localStorage.setItem(MA_KEY,JSON.stringify(data));maRender();return}const f=file.files[0];if(!f)return alert("Bitte zuerst eine PDF oder ein Bild auswählen.");const id=crypto.randomUUID?crypto.randomUUID():String(Date.now()),data=JSON.parse(localStorage.getItem(MA_KEY)||"[]");data.unshift({id,name:M("name").value||f.name,amount:chosen==="Versicherung"?0:+M("amount").value||0,minimum:+M("minimum")?.value||0,due:chosen==="Versicherung"?"":M("due").value,no:M("no").value,cat:maCat(chosen),type:chosen,status:chosen==="Mahnung"?"Mahnstufe 1":"Archiviert",rem:+M("rem").value||0,paid:false,paidDate:"",file:f.name});await maPut(id,f);localStorage.setItem(MA_KEY,JSON.stringify(data));maRender();file.value="";const a=M("filePreview");if(a){a.hidden=true;a.removeAttribute("href")}M("preview").innerHTML="Noch kein Dokument analysiert.";alert("Dokument archiviert.")};
const search=M("search");if(search)search.oninput=maRender;document.querySelectorAll(".tab").forEach(b=>{const n=b.cloneNode(true);b.replaceWith(n);n.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));n.classList.add("active");maRender()}});maRender();})();