const V18KEY="ma11";
const V18=$=>document.getElementById($);
const v18Money=n=>new Intl.NumberFormat("de-CH",{style:"currency",currency:"CHF",minimumFractionDigits:2}).format(Number(n)||0);
const v18Esc=s=>String(s??"").replace(/[&<>\"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;","'":"&#39;"}[m]));
const v18Date=s=>s?new Date(s+"T00:00:00").toLocaleDateString("de-CH"):"";
function v18Type(x){if(x.type)return x.type;if(x.minimum>0)return "Kreditkartenabrechnung";if(x.amount>0)return "Rechnung";return "Dokument";}
function v18IsBill(x){const t=v18Type(x);return t==="Rechnung"||t==="Kreditkartenabrechnung";}
function v18Render(){
 const data=JSON.parse(localStorage.getItem(V18KEY)||"[]"),q=(V18("search")?.value||"").toLowerCase(),list=V18("list");if(!list)return;
 const items=data.filter(x=>!q||(x.name+" "+x.no+" "+x.cat+" "+v18Type(x)+" "+(x.status||"")).toLowerCase().includes(q));
 list.innerHTML=items.length?items.map(x=>{const type=v18Type(x),bill=v18IsBill(x),status=bill?(x.paid?"Bezahlt":"Offen"):(x.status||"Archiviert"),badge=bill?(x.paid?"paid":"future"):type==="Mahnung"?"danger":"future",details=[x.due?v18Date(x.due):"",x.no?"Nr. "+v18Esc(x.no):""].filter(Boolean).join(" · "),min=x.minimum>0?`<div class="muted">💳 Mindestbetrag: ${v18Money(x.minimum)}</div>`:"",amount=bill&&x.amount?v18Money(x.amount):"📄 Dokument";return `<article class="doc"><b>${v18Esc(x.name||x.file)}</b><div class="amount">${amount}</div>${min}<div class="muted">${v18Esc(type)} · ${v18Esc(x.cat||"Sonstiges")}${details?"<br>"+details:""}</div><span class="badge ${badge}">${status}</span><div class="actions"><button class="btn outline" onclick="openPDF('${v18Esc(x.id)}')">📄 Öffnen</button>${bill?`<button class="btn ${x.paid?'gray':'green'}" onclick="window.maToggle&&maToggle('${v18Esc(x.id)}')">${x.paid?"↩ Wieder öffnen":"✓ Als erledigt markieren"}</button>`:""}</div></article>`}).join(""):"<div class='empty'>Keine Dokumente.</div>";
 const bills=data.filter(x=>!x.paid&&v18IsBill(x));V18("openCount").textContent=bills.length;V18("openAmount").textContent=v18Money(bills.reduce((a,x)=>a+(+x.amount||0),0));V18("soonCount").textContent=bills.filter(x=>x.due).length;
}
async function v18ReadText(file){if(file.type!=="application/pdf")return "";const p=await import("https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.min.mjs");p.GlobalWorkerOptions.workerSrc="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.worker.min.mjs";const pdf=await p.getDocument({data:await file.arrayBuffer()}).promise;let text="";for(let i=1;i<=pdf.numPages;i++){const c=await(await pdf.getPage(i)).getTextContent();text+=c.items.map(a=>a.str).join(" ")+"\n"}return text;}
function v18PolicyNo(t){for(const p of [/(?:Policenummer|Policen\s*(?:Nr\.?|Nummer)|Police\s*(?:Nr\.?|Nummer)|Versicherungsnummer|Versicherung\s*(?:Nr\.?|Nummer)|Vertragsnummer|Vertrag\s*(?:Nr\.?|Nummer))\s*[:#\-]?\s*([A-Z0-9][A-Z0-9\-\/\. ]{3,40})/i,/(?:Police|Police-Nr\.?|Police\s*Nr\.?)\s*[:#\-]?\s*([A-Z0-9][A-Z0-9\-\/\.]{3,40})/i]){const m=t.match(p);if(m)return m[1].replace(/\s+/g," ").trim()}return "";}
function v18FixInsuranceForm(){const type=V18("docType"),amount=V18("amount"),due=V18("due"),no=V18("no");if(!type||type.value!=="Versicherung")return;if(amount)amount.value="";if(due)due.value="";const lab=[...document.querySelectorAll("label")].find(x=>x.textContent.trim()==="Rechnungsnummer");if(lab)lab.textContent="Policen-/Vertragsnummer";if(V18("cat"))V18("cat").value="Versicherungen";if(V18("preview"))V18("preview").innerHTML=`<b>🧠 Dokumenttyp:</b> Versicherung · <b>Kategorie:</b> Versicherungen<br>🛡️ Policen-/Vertragsnummer: ${v18Esc(no?.value||"nicht erkannt")}<br>💰 Kein Rechnungsbetrag aus der Police übernommen.<br><span class="muted">👁️ Original kann über die Vorschau geöffnet werden.</span>`;}
(async()=>{await new Promise(r=>setTimeout(r,120));const file=V18("file");if(!file)return;const p=document.querySelector("header p");if(p)p.textContent="Dein persönliches Dokumenten- & Rechnungsarchiv · v18";document.title="MeinArchiv v18";const oldToggle=window.maToggle;if(oldToggle)window.maToggle=id=>{oldToggle(id);setTimeout(v18Render,80)};file.addEventListener("change",async()=>{setTimeout(async()=>{const type=V18("docType");if(!type)return;if(type.value==="Versicherung"){v18FixInsuranceForm();const f=file.files?.[0];if(f&&!V18("no")?.value){try{const n=v18PolicyNo(await v18ReadText(f));if(n)V18("no").value=n}catch{}}v18FixInsuranceForm();}},80);});const save=V18("save");if(save)save.addEventListener("click",()=>setTimeout(v18Render,250));const search=V18("search");if(search)search.addEventListener("input",v18Render);document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>setTimeout(v18Render,20)));v18Render();})();