const V19KEY="ma11", V19DB="ma11files";
const V19=$=>document.getElementById($);
const v19Money=n=>new Intl.NumberFormat("de-CH",{style:"currency",currency:"CHF",minimumFractionDigits:2}).format(Number(n)||0);
const v19Esc=s=>String(s??"").replace(/[&<>\"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;","'":"&#39;"}[m]));
const v19Date=s=>s?new Date(s+"T00:00:00").toLocaleDateString("de-CH"):"";
function v19TypeFromText(t){const x=(t||"").toLowerCase();if(/mahnung|zahlungserinnerung|letzte zahlungserinnerung/.test(x))return"Mahnung";if(/kreditkarte|credit\s*card|kartenabrechnung|card\s*statement|visa|mastercard|cembra/.test(x))return"Kreditkartenabrechnung";if(/arbeitsvertrag|mietvertrag|kaufvertrag|vertrag|vereinbarung/.test(x))return"Vertrag";if(/versicherung|police|policenummer|versicherungsnummer|prämienrechnung/.test(x))return"Versicherung";if(/lohnabrechnung|gehaltsabrechnung|lohnausweis|salary statement/.test(x))return"Lohnabrechnung";if(/garantie|garantieschein|kaufbeleg|kassenbon|quittung/.test(x))return"Kaufbeleg / Garantie";if(/kontoauszug|bankauszug|zinsabrechnung/.test(x))return"Bankdokument";if(/steuer|steueramt|veranlagung|behörde|gemeinde|kanton|bundesamt/.test(x))return"Behörde / Steuer";if(/rechnung|rechnungsbetrag|zahlbar bis|zahlungsziel|zu bezahlen/.test(x))return"Rechnung";return"Dokument"}
function v19Cat(type){return ({"Rechnung":"Finanzen","Kreditkartenabrechnung":"Finanzen","Mahnung":"Mahnungen","Vertrag":"Verträge","Versicherung":"Versicherungen","Lohnabrechnung":"Finanzen","Kaufbeleg / Garantie":"Käufe & Garantien","Bankdokument":"Finanzen","Behörde / Steuer":"Behörden","Dokument":"Sonstiges"}[type]||"Sonstiges")}
function v19PolicyNo(t){for(const p of [/(?:Policenummer|Police\s*(?:Nr\.?|Nummer)|Policen\s*(?:Nr\.?|Nummer)|Versicherungsnummer|Versicherung\s*(?:Nr\.?|Nummer)|Vertragsnummer|Vertrag\s*(?:Nr\.?|Nummer))\s*[:#\-]?\s*([A-Z0-9][A-Z0-9\-\/\. ]{3,40})/i,/(?:Police|Police-Nr\.?|Police\s*Nr\.?)\s*[:#\-]?\s*([A-Z0-9][A-Z0-9\-\/\.]{3,40})/i]){const m=t.match(p);if(m)return m[1].replace(/\s+/g," ").trim()}return""}
function v19Open(){return new Promise((res,rej)=>{const r=indexedDB.open(V19DB,1);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function v19Put(id,file){const db=await v19Open();return new Promise((res,rej)=>{const tx=db.transaction("f","readwrite");tx.objectStore("f").put(file,id);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
async function v19ReadPDF(file){const p=await import("https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.min.mjs");p.GlobalWorkerOptions.workerSrc="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.worker.min.mjs";const pdf=await p.getDocument({data:await file.arrayBuffer()}).promise;let text="";for(let i=1;i<=pdf.numPages;i++){const c=await(await pdf.getPage(i)).getTextContent();text+=c.items.map(a=>a.str).join(" ")+"\n"}return{text,pages:pdf.numPages}}
function v19Preview(file){let a=V19("filePreview");if(!a){a=document.createElement("a");a.id="filePreview";a.className="btn outline wide";a.target="_blank";a.rel="noopener";a.style.display="block";a.style.textAlign="center";a.style.textDecoration="none";a.style.marginTop="10px";V19("file").parentNode.insertBefore(a,V19("file").nextSibling)}if(a.dataset.url)URL.revokeObjectURL(a.dataset.url);const u=URL.createObjectURL(file);a.dataset.url=u;a.href=u;a.textContent="👁️ Dokumentvorschau öffnen";a.hidden=false}
function v19Status(x){if(x.type==="Rechnung"||x.type==="Kreditkartenabrechnung"||x.minimum>0)return x.paid?"🟢 Bezahlt":"🔴 Offen";if(x.type==="Mahnung")return x.status||"🔴 Mahnstufe 1";return x.status||"📁 Archiviert"}
function v19Render(){const data=JSON.parse(localStorage.getItem(V19KEY)||"[]"),q=(V19("search")?.value||"").toLowerCase(),list=V19("list");if(!list)return;const items=data.filter(x=>!q||(x.name+" "+x.no+" "+x.cat+" "+x.type+" "+x.status).toLowerCase().includes(q));list.innerHTML=items.length?items.map(x=>{const bill=x.type==="Rechnung"||x.type==="Kreditkartenabrechnung"||x.minimum>0;const amount=bill&&x.amount?v19Money(x.amount):"📄 Dokument";const min=x.minimum>0?`<div class="muted">💳 Mindestbetrag: ${v19Money(x.minimum)}</div>`:"";const details=[x.due?v19Date(x.due):"",x.no?"Nr. "+v19Esc(x.no):""].filter(Boolean).join(" · ");const st=v19Status(x);const cls=x.paid?"paid":x.type==="Mahnung"?"danger":bill?"future":"soon";return `<article class="doc"><b>${v19Esc(x.name||x.file)}</b><div class="amount">${amount}</div>${min}<div class="muted">${v19Esc(x.type||"Dokument")} · ${v19Esc(x.cat||"Sonstiges")}${details?"<br>"+details:""}</div><span class="badge ${cls}">${st}</span><div class="actions"><button class="btn outline" onclick="openPDF('${v19Esc(x.id)}')">📄 Öffnen</button>${bill?`<button class="btn ${x.paid?'gray':'green'}" onclick="v19Toggle('${v19Esc(x.id)}')">${x.paid?"↩ Wieder öffnen":"✓ Als bezahlt markieren"}</button>`:""}</div></article>`}).join(""):"<div class='empty'>Keine Dokumente.</div>";const bills=data.filter(x=>!x.paid&&(x.type==="Rechnung"||x.type==="Kreditkartenabrechnung"||x.minimum>0));V19("openCount").textContent=bills.length;V19("openAmount").textContent=v19Money(bills.reduce((a,x)=>a+(+x.amount||0),0));V19("soonCount").textContent=bills.filter(x=>x.due).length}
window.v19Toggle=id=>{const data=JSON.parse(localStorage.getItem(V19KEY)||"[]"),x=data.find(a=>a.id===id);if(x){x.paid=!x.paid;x.paidDate=x.paid?new Date().toISOString().slice(0,10):"";localStorage.setItem(V19KEY,JSON.stringify(data));v19Render()}};
function v19Reset(){["name","amount","minimum","due","no"].forEach(id=>{if(V19(id))V19(id).value=""});if(V19("minimumWrap"))V19("minimumWrap").hidden=true;if(V19("preview"))V19("preview").innerHTML="Noch kein Dokument analysiert.";const a=V19("filePreview");if(a){a.hidden=true;if(a.dataset.url)URL.revokeObjectURL(a.dataset.url);a.remove()}}
(async()=>{await new Promise(r=>setTimeout(r,180));const file=V19("file"),save=V19("save");if(!file||!save)return;const p=document.querySelector("header p");if(p)p.textContent="Dein persönliches Dokumenten- & Rechnungsarchiv · v19";document.title="MeinArchiv v19";
let type=V19("docType");if(!type){const wrap=document.createElement("div");wrap.innerHTML='<label>Dokumenttyp</label><select id="docType"><option>Automatisch erkennen</option><option>Rechnung</option><option>Kreditkartenabrechnung</option><option>Mahnung</option><option>Vertrag</option><option>Versicherung</option><option>Lohnabrechnung</option><option>Kaufbeleg / Garantie</option><option>Bankdokument</option><option>Behörde / Steuer</option><option>Dokument</option></select>';V19("cat").parentNode.insertBefore(wrap,V19("cat"));type=V19("docType")}
file.addEventListener("change",async()=>{const f=file.files?.[0];if(!f)return;v19Preview(f);V19("status").textContent="🧠 Dokument wird gelesen …";let text="";try{if(f.type==="application/pdf"){text=(await v19ReadPDF(f)).text}else{const{createWorker}=await import("https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.esm.min.js");const w=await createWorker("deu+eng+fra"),r=await w.recognize(await f.arrayBuffer());text=r.data.text||"";await w.terminate()}}catch(e){console.error(e)}const detected=v19TypeFromText(text+" "+f.name);if(type.value==="Automatisch erkennen")type.value=detected;const chosen=type.value;
if(chosen==="Versicherung"){V19("amount").value="";V19("due").value="";if(V19("minimumWrap"))V19("minimumWrap").hidden=true;const n=v19PolicyNo(text);if(n)V19("no").value=n;const lab=[...document.querySelectorAll("label")].find(x=>x.textContent.trim()==="Rechnungsnummer");if(lab)lab.textContent="Policen-/Vertragsnummer";V19("cat").value="Versicherungen";V19("preview").innerHTML=`<b>🧠 Dokumenttyp:</b> Versicherung · <b>Kategorie:</b> Versicherungen<br>🛡️ Policen-/Vertragsnummer: ${v19Esc(V19("no").value||"nicht erkannt")}<br>💰 Kein Rechnungsbetrag aus der Police übernommen.<br><span class="muted">👁️ Vorschau oben ist bereit.</span>`;
}else{const lab=[...document.querySelectorAll("label")].find(x=>x.textContent.trim()==="Policen-/Vertragsnummer");if(lab)lab.textContent="Rechnungsnummer";if(chosen==="Kreditkartenabrechnung")V19("minimumWrap").hidden=false;V19("cat").value=v19Cat(chosen);V19("preview").innerHTML=`<b>🧠 Dokumenttyp:</b> ${v19Esc(chosen)} · <b>Kategorie:</b> ${v19Esc(V19("cat").value)}<br><span class="muted">👁️ Vorschau oben ist bereit. Bitte Felder kontrollieren.</span>`}V19("status").textContent=text?"✅ Dokument analysiert.":"⚠️ Kein Text erkannt – bitte Daten kontrollieren.";});
if(type)type.addEventListener("change",()=>{const chosen=type.value;if(chosen==="Versicherung"){V19("amount").value="";V19("due").value="";if(V19("minimumWrap"))V19("minimumWrap").hidden=true;V19("cat").value="Versicherungen";const lab=[...document.querySelectorAll("label")].find(x=>x.textContent.trim()==="Rechnungsnummer");if(lab)lab.textContent="Policen-/Vertragsnummer"}else{const lab=[...document.querySelectorAll("label")].find(x=>x.textContent.trim()==="Policen-/Vertragsnummer");if(lab)lab.textContent="Rechnungsnummer";if(V19("minimumWrap"))V19("minimumWrap").hidden=chosen!=="Kreditkartenabrechnung";if(chosen!=="Automatisch erkennen")V19("cat").value=v19Cat(chosen)}});
save.onclick=async()=>{const f=file.files?.[0];if(!f)return alert("Bitte zuerst eine PDF oder ein Bild auswählen.");const chosen=type.value==="Automatisch erkennen"?"Dokument":type.value;const data=JSON.parse(localStorage.getItem(V19KEY)||"[]");const id=crypto.randomUUID?crypto.randomUUID():String(Date.now());const amount=chosen==="Versicherung"?0:(+V19("amount").value||0);if((chosen==="Rechnung"||chosen==="Kreditkartenabrechnung")&&!amount)return alert("Bitte den Rechnungsbetrag kontrollieren.");if((chosen==="Rechnung"||chosen==="Kreditkartenabrechnung")&&!V19("due").value)return alert("Bitte das Fälligkeitsdatum kontrollieren.");const item={id,name:V19("name").value||f.name,amount:+amount.toFixed(2),minimum:+(+V19("minimum")?.value||0).toFixed(2),due:chosen==="Versicherung"?"":V19("due").value,no:V19("no").value,cat:chosen==="Versicherung"?"Versicherungen":V19("cat").value,type:chosen,status:(chosen==="Mahnung"?"Mahnstufe 1":chosen==="Rechnung"||chosen==="Kreditkartenabrechnung"?"Offen":"Archiviert"),rem:+V19("rem").value||0,paid:false,paidDate:"",file:f.name};data.unshift(item);await v19Put(id,f);localStorage.setItem(V19KEY,JSON.stringify(data));v19Render();file.value="";v19Reset();alert("Dokument archiviert.")};
const search=V19("search");if(search)search.addEventListener("input",v19Render);document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>setTimeout(v19Render,30)));v19Render();})();